Auto release script
scientist-softserv/west-virginia-university pull request #66
Opened 2023-04-17 23:55 UTC by orangewolf

Adds a script to poll Github for new releases. This changes the code update for the dev and prod servers to be set to either pre-release tags or latest release tags respectively.  If the code is updated, it will run migrations, build the containers and restart the conversion, web and workers containers.

To enable on the dev server, add 
`*/5 * * * * bash -l -c "cd /home/git_pulls/hydra_acda_portal_public; ./check_new_release.sh dev"`

2023-04-18 15:20 UTC, alishaevn requested changes

2023-04-18 15:20 UTC, alishaevn commented on README.md
> +There isn't any way to script all of this without lots of pre-planning and forcing hydra to adhear to a certain standard.
```suggestion
There isn't any way to script all of this without lots of pre-planning and forcing hydra to adhere to a certain standard.
```

2023-04-18 15:20 UTC, alishaevn commented on README.md
> +There isn't any way to script all of this without lots of pre-planning and forcing hydra to adhear to a certain standard.
I know this was preexisting, but since we're already making changes to this file... 🙃

2023-04-18 17:10 UTC, sephirothkod commented on check_new_release.sh
> +#!/bin/bash
Yes this script is assuming that it is in the root folder to do the github pull (which has to be done in the root).

2023-04-24 18:49 UTC, merged

2023-04-24 19:10 UTC, alishaevn reviewed
approved!